Solve the missing hasAttributes() problem
The following exception is fixed:

Traceback (most recent call last):
  File "analyze.py", line 202, in <module>
    main()
  File "analyze.py", line 199, in main
    zip.analyze()
  File "analyze.py", line 108, in analyze
    parser.parseOdfFile(odtFile)
  File "/home/laban/proj/eucrcon/parser.py", line 261, in parseOdfFile
    nam,typ,ans = parser(filename)
  File "/home/laban/proj/eucrcon/parser.py", line 312, in parser
    respondAns = findAnswers(doc, questions, openquest, styleTag, numberingTag)
  File "/home/laban/proj/eucrcon/parser.py", line 153, in findAnswers
    numberOfCountAttribute = countTag(element, tag)
  File "/home/laban/proj/eucrcon/parser.py", line 131, in countTag
    if findAttributeRecursive(element, tag):
  File "/home/laban/proj/eucrcon/parser.py", line 21, in findAttributeRecursive
    if node.nodeType != node.TEXT_NODE and node.hasAttributes():
AttributeError: 'ProcessingInstruction' object has no attribute 'hasAttributes'